### PR TITLE
query: fix include-related.

### LINKED ISSUE #1924: Missing rest of thread context when searching for (from:self)
## Expected or desired behavior

When I search for threads I'm participating in with:

    (recip:alex.bennee OR recip:bennee.com)
  
I expect the rest of the thread to show up.
  
## Actual behaviour

Please describe the behavior you are actually seeing.

I get a mixed picture. For some threads it seems to show up but for some others I just get the email I sent. The email has a proper In-reply-to header and if I search for that id I get the whole thread in question.

This appears to be a result of the recent threading changes.

## Versions of mu, mu4e/emacs, operating system etc.

Current mu git HEAD, emacs native-comp branch, Linux Debian 10

### PR DESCRIPTION
**Pull request by nicolasavru**
mu-query.cc:
- make_related_enquire: don't include first query in qvec, we already have all
  thread IDs we need to query in thread_ids.
- run_related: always sort first query by date, as explained in the code
  comment.
- run_related: include qflags (in particular ascending vs descending) in
  leader_qflags.
- run_threaded: don't limit results to maxnum, that results in threads
  potentially being cut off.

mu-server.cc:
- output_sexp: don't limit results to maxnum so as to match the behaviour of
  mu find (and avoid cutting off threads).

Fixes #1924 and #1911.

### CODE REVIEW

File: lib/mu-query.cc [hunk 1]
```diff
@@ -192,12 +190,12 @@ Query::Private::run_related (const std::string& expr, MuMsgFieldId sortfieldid,
...
-        const auto leader_qflags{QueryFlags::Leader};
+        const auto leader_qflags{QueryFlags::Leader | qflags};
         const auto threading{any_of(qflags & QueryFlags::Threading)};
 
         // Run our first, "leader" query
         DeciderInfo minfo{};
-        auto enq{make_enquire(expr, sortfieldid, leader_qflags)};
+        auto enq{make_enquire(expr, MU_MSG_FIELD_ID_DATE, leader_qflags)};
         const auto mset{enq.get_mset(0, maxnum, {},
                                      make_leader_decider(leader_qflags, minfo).get())};
```
Comment (nicolasavru) [inline lib/mu-query.cc:201]: It just occurred to me... shouldn't we be gathering message IDs here, not thread IDs? Also, how are thread IDs populated in the db (as in, how are they generated, what actually are they) if threading is calculated after this point?

Comment (nicolasavru) [reply lib/mu-query.cc:201]: Ah, I think I remember how this works now... there should be a 1:1 correspondence between message IDs and thread IDs, so this should work...

**Comment by djcb** [comment]
I've played with for the last days, and it worked well for me (though admittedly, I never really encountered the original issue).

Anyway, merged.... Thanks for working on this!
